services:
    product_client:
        class: Gigabit\AffilinetBundle\Service\ProductClientService
        arguments: ['@service_container', '', '']
    publisher_client:
        class: Gigabit\AffilinetBundle\Service\PublisherClientService
        arguments: ['@service_container', '', '']

    shop:
        class: Gigabit\AffilinetBundle\Service\ShopService
        arguments: ['@product_client']
    category:
        class: Gigabit\AffilinetBundle\Service\CategoryService
        arguments: ['@product_client']
    product:
        class: Gigabit\AffilinetBundle\Service\ProductService
        arguments: ['@product_client']
    program:
      class: Gigabit\AffilinetBundle\Service\ProgramService
      arguments: ['@publisher_client']