services:
    affilinet.product_client:
        class: Gigabit\AffilinetBundle\Service\ProductClientService
        arguments: ['@service_container', '', '']
    affilinet.publisher_client:
        class: Gigabit\AffilinetBundle\Service\PublisherClientService
        arguments: ['@service_container', '', '']

    affilinet.shop:
        class: Gigabit\AffilinetBundle\Service\ShopService
        arguments: ['@product_client']
    affilinet.category:
        class: Gigabit\AffilinetBundle\Service\CategoryService
        arguments: ['@product_client']
    affilinet.product:
        class: Gigabit\AffilinetBundle\Service\ProductService
        arguments: ['@product_client']
    affilinet.program:
      class: Gigabit\AffilinetBundle\Service\ProgramService
      arguments: ['@publisher_client']
    affilinet.creative:
      class: Gigabit\AffilinetBundle\Service\CreativeService
      arguments: ['@publisher_client']
