services:
    affilinet.product_client:
        class: Gigabit\AffilinetBundle\Service\ProductClientService
        arguments: ['@service_container', '', '']
    affilinet.publisher_client:
        class: Gigabit\AffilinetBundle\Service\PublisherClientService
        arguments: ['@service_container', '', '']

    affilinet.shop:
        class: Gigabit\AffilinetBundle\Service\ShopService
        arguments: ['@affilinet.product_client']
    affilinet.category:
        class: Gigabit\AffilinetBundle\Service\CategoryService
        arguments: ['@affilinet.product_client']
    affilinet.product:
        class: Gigabit\AffilinetBundle\Service\ProductService
        arguments: ['@affilinet.product_client']
    affilinet.program:
      class: Gigabit\AffilinetBundle\Service\ProgramService
      arguments: ['@affilinet.publisher_client']
    affilinet.creative:
      class: Gigabit\AffilinetBundle\Service\CreativeService
      arguments: ['@affilinet.publisher_client']
    affilinet.statistics:
      class: Gigabit\AffilinetBundle\Service\StatisticsService
      arguments: ['@affilinet.publisher_client', '%gigabit_affilinet.partnership_start%']